### ISSUE TITLE
Guida per gente che non usa il prompt dei comandi

### ISSUE THREAD

**Issue by Farfi55** [skilion/reddit-place-italy#1]
non conoscendo nessuna funzione del prompt dei comandi trovo molto difficile avviare il programma.
Vi sarei molto riconoscente se mi indicherete passo per passo (come entrare in una cartella etc...) come fare!

**Comment by skilion** [comment]
Se hai windows 10, SHIFT+tasto destro del mouse sulla cartella, "Apri finestra di comando qui"

**Comment by nicolo-ribaudo** [comment]
Oppure con `cd percorso/relativo/alla/cartella/dove/ti/trovi/nel/prompt`

**Comment by skilion** [comment]
Ciao, vi faccio notare che questo repo è già vecchio. Se avete il programma installato passate al nuovo fork https://github.com/theitalyplace/reddit-place-italy
