### ISSUE TITLE
GUIDA: Installazione su Android

### ISSUE THREAD

**Issue by nicolo-ribaudo** [skilion/reddit-place-italy#2]
Ho scritto questa guida a memoria dopo aver provato, quindi potrebbero esserci degli errori. Se è così, avvisatemi che la aggiorno

## 1. Installare le app necessarie

- Termux, un prompt dei comandi per Android (https://play.google.com/store/apps/details?id=com.termux)
- Hacker's Keyboard, una tastiera con le frecce per spostarsi e il tasto ctrl (https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)

Dopo aver installato Hacker's Keyboard, abilitarla e nelle sue impostazioni selezionare il layout completo

Poi aprire Termux, tutti i punti successivi sono da eseguire lì dentro

## 2. Installare node e gli altri pacchetti necessari

- Aggiornare apt, che serve a installare i pacchetti
```
apt update && apt upgrade
```

- Installare le librerie necessarie
```
apt install coreutils nodejs git nano
```

## 3. Scaricare il bot
```
git clone https://github.com/theitalyplace/reddit-place-italy
cd reddit-place-italy
npm install
```

## 4. Creare il file users.json

```
cp users.EMPTY.json users.json
nano users.json
```

Nano aprirà una specie di editor di testo. Modificate il file (per spostarsi usare le frecce di Hacker's Keyboard). Per uscire e salvare fate `Ctrl+X`, poi `y` e due volte enter.
Se volete modificare il link dell'immagine target, usate di nuovo nano sul file diff.js e cambiare il link di target.png (in una linea che inizia con `request('https://`), facendo attenzione a lasciare gli apici intorno all'url.

## 5. Far partire il bot!

```
npm start
```

## 6. Evitare che Termux vada in pausa

Nella notifica di Termux, toccare su "Acquire wakelock"

**Comment by skilion** [comment]
Ciao, ottimo lavoro.
Le cose si muovono velocemente è questo repo è gia vecchio. Se hai il programma installato passa al nuovo fork https://github.com/theitalyplace/reddit-place-italy e carica li questa guida.
